AWSTemplateFormatVersion: '2010-09-09'
Description: aws-network-basis cfn tutorial.
Resources:
  # 第二章
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: "Name"
          Value: "MyVPC"
  MyPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref MyVPC
      Tags:
        - Key: "Name"
          Value: "MyPublicSubnet"
  MyGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: "Name"
          Value: "MyInternetGateway"
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref MyGateway
      VpcId: !Ref MyVPC
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: "Name"
          Value: "MyRouteTable"
  MyRoute:
    Type: "AWS::EC2::Route"
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyGateway
      RouteTableId: !Ref MyRouteTable
  MySubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref MyRouteTable
      SubnetId: !Ref MyPublicSubnet
  # 第三章
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "WEB-SG"
      GroupDescription: "aws-network-basis SecurityGroup"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: "SSH"
          IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          Description: "HTTP"
          IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
      VpcId: !Ref MyVPC
  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0a2de1c3b415889d2"
      InstanceType: "t2.micro"
      KeyName: "MyKeypair"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          PrivateIpAddress: 10.0.1.10
          SubnetId: !Ref MyPublicSubnet
          GroupSet:
            - !Ref MySecurityGroup
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: "standard"
            VolumeSize: 8
      Tags:
        - Key: Name
          Value: "Web Server"
  MyEIP:
    Type: AWS::EC2::EIP
    DependsOn: MyVPC
    Properties:
      InstanceId: !Ref MyInstance
      Domain: vpc
  # 第四章
